name: Fiyat Güncelle

on:
  schedule:
    - cron: '*/1 * * * *'
  workflow_dispatch:

jobs:
  update-prices:
    runs-on: ubuntu-latest

    steps:
      - name: Repo'yu klonla
        uses: actions/checkout@v3

      - name: Python kurulumu
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Gerekli kütüphaneleri yükle
        run: |
          pip install -r requirements.txt

      - name: Fiyatları güncelle
        run: |
          python fiyat.py

      - name: Git ayarları ve push işlemi
        run: |
          git config --global user.name "yssaydam"
          git config --global user.email "yavuzselimsaydam@gmail.com"
          git add .
          git commit -m "🔁 Otomatik fiyat güncelleme"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
